name: 'Turbo Monorepo Release Action'
description: |
  Creates a GitHub release from a commit range.
  Filters the commit range by two criteria:

  1. The commits must match conventional commit format
  2. The commits must trigger a turbo build for the workspace

  Commit range is inclusive, both from
  and to is included in the release.
author: 'Adventure Tech AS'

# Define your inputs here.
inputs:
  github-token:
    description: 'A github token used to create the release'
    required: true
  prefix:
    description: 'The prefix of the release tag (e.g. my-app)'
    required: true
  workspace:
    description: 'The turbo workspace name used to filter commits, (e.g. my-app)'
    required: true
  from:
    description: 'First commit in the release'
    required: true
  to:
    description: 'Last commit in the release'
    required: true

# Define your outputs here.
outputs:
  release-url:
    description: 'The GitHub release URL for the created release'
  release-title:
    description: 'The release title for the created release'
  release-body:
    description: 'The release body for the created release'

runs:
  using: node20
  main: dist/index.js
