name: 'Create release from deployment'
description: |
  Creates a GitHub release from a deployment.
  Uses the commits between the previous deployment
  and the current one to find the commit messages.
  Filters commits to conventional commits and those
  that trigger a turbo build (using turbo workspaces).
author: 'Adventure Tech AS'

# Define your inputs here.
inputs:
  github-environment:
    description: 'The environment you deployed (e.g. staging, production)'
    required: true
  github-token:
    description: 'A github token used to fetch deployments and creating the release'
    required: true
  prefix:
    description: 'The prefix of the release tag (e.g. my-app)'
    required: true
  workspace:
    description: 'The turbo workspace name used to filter commits, (e.g. my-app)'
    required: true

# Define your outputs here.
outputs:
  release-url:
    description: 'The GitHub release URL for the created release'
  release-title:
    description: 'The release title for the created release'
  release-body:
    description: 'The release body for the created release'

runs:
  using: node20
  main: dist/index.js
